import React, { useState } from 'react';
import { aiService } from '../services/api';
import { Brain, Sparkles, RefreshCw, AlertCircle } from 'lucide-react';
import './AiSummary.css';

const AiSummary = ({ projectId, detailed = false }) => {
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateSummary = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await aiService.generateProjectSummary(projectId);
      setSummary(response.summary);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate summary');
      console.error('AI Summary error:', err);
    } finally {
      setLoading(false);
    }
  };

  const generateWeeklySummary = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await aiService.generateWeeklySummary();
      setSummary(response.summary);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate weekly summary');
      console.error('AI Weekly Summary error:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="ai-summary">
      <div className="ai-summary-header">
        <div className="ai-title">
          <Brain size={20} />
          <h3>AI Project Summary</h3>
          <Sparkles size={16} className="sparkle" />
        </div>
        
        {detailed && (
          <div className="ai-actions">
            <button 
              className="btn btn-secondary btn-sm"
              onClick={generateSummary}
              disabled={loading}
            >
              {loading ? <RefreshCw size={14} className="spinning" /> : <RefreshCw size={14} />}
              Project Summary
            </button>
            <button 
              className="btn btn-primary btn-sm"
              onClick={generateWeeklySummary}
              disabled={loading}
            >
              {loading ? <RefreshCw size={14} className="spinning" /> : <Sparkles size={14} />}
              Weekly Summary
            </button>
          </div>
        )}
      </div>

      {error && (
        <div className="alert alert-error">
          <AlertCircle size={16} />
          {error}
        </div>
      )}

      {loading ? (
        <div className="ai-summary-loading">
          <div className="spinner"></div>
          <p>AI is analyzing your project data...</p>
        </div>
      ) : summary ? (
        <div className="ai-summary-content">
          <div className="summary-text">
            {summary.split('\n').map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
          </div>
          {!detailed && (
            <button 
              className="btn btn-secondary btn-sm"
              onClick={generateSummary}
            >
              <RefreshCw size={14} />
              Regenerate
            </button>
          )}
        </div>
      ) : (
        <div className="ai-summary-empty">
          <Brain size={48} className="empty-icon" />
          <h4>No summary generated yet</h4>
          <p>
            {detailed 
              ? 'Click one of the buttons above to generate an AI-powered summary of your project.'
              : 'Generate an AI summary to get insights about your project activity.'
            }
          </p>
          {!detailed && (
            <button 
              className="btn btn-primary"
              onClick={generateSummary}
            >
              <Sparkles size={16} />
              Generate Summary
            </button>
          )}
        </div>
      )}

      {detailed && summary && (
        <div className="ai-summary-footer">
          <div className="disclaimer">
            <AlertCircle size={14} />
            <span>This summary is generated by AI and may not be perfect. Always verify critical information.</span>
          </div>
        </div>
      )}
    </div>
  );
};

export default AiSummary;